export const ROUTE_PATHS = {
    home: '/',
    products: '/products',
    productDetail: '/products/:id',
    recipes: '/recipes',
    recipeDetail: '/recipes/:slug',
    login: '/login',
    register: '/register',
    cart: '/cart',
    checkout: '/checkout',
    profile: '/profile',
    payment: '/payment/:orderId',
    orders: '/orders',
    orderDetail: '/orders/:id',
    admin: '/admin',
    adminProducts: '/admin/products',
    adminProductCreate: '/admin/products/new',
    adminProductEdit: '/admin/products/:id/edit',
    adminRecipes: '/admin/recipes',
    adminRecipeCreate: '/admin/recipes/new',
    adminRecipeEdit: '/admin/recipes/:id/edit',
    adminVouchers: '/admin/vouchers',
    adminOrders: '/admin/orders',
    adminOrderDetail: '/admin/orders/:id',
    adminUsers: '/admin/users',
} as const;
